(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 15:46 on 16.12.2015 *) 
 
 
PrintDebug["   ... ",TreeS2L2u]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]}; 
 NamesOperators =  {TSOlluuSLL, TSOlluuSRR, TSOlluuSRL, TSOlluuSLR, TSOlluuVRR, TSOlluuVLL, TSOlluuVRL, TSOlluuVLR, TSOlluuTLL, TSOlluuTLR, TSOlluuTRL, TSOlluuTRR}; 
 NeglectInsertionOrderTree[TreeS2L2u] =  {}; 
NeglectCrossedDiagrams[TreeS2L2u] = False; 
NameProcess = TreeS2L2u; 
 
Generate[TreeS2L2u][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],UpQuark,bar[UpQuark],TreeS2L2u,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeS2L2u][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeS2L2u] = masses 
]; 

WriteCodeObservablePreSARAH[TreeS2L2u][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeS2L2u] = masses; 
NeededCouplingsAllSaved[TreeS2L2u] = couplings; 
NeededCombinations[TreeS2L2u] = {{2, 1, 1, 1}, {3, 1, 1, 1}, {3, 2, 1, 1}}; 
PrintDebug["     writing SPheno code for ",TreeS2L2u]; 
MakeSubroutineTitle["CalculateTreeS2L2u",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TSOlluuSLL", "TSOlluuSRR", "TSOlluuSRL", "TSOlluuSLR", "TSOlluuVRR", "TSOlluuVLL", "TSOlluuVRL", "TSOlluuVLR", "TSOlluuTLL", "TSOlluuTLR", "TSOlluuTRL", "TSOlluuTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeS2L2u \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 15:46 on 16.12.2015 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuSLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuSRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuSRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuSLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSOlluuTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeS2L2u' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[UpQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[UpQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[UpQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[UpQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], UpQuark, bar[UpQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], UpQuark[{gt3}], bar[UpQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TSOlluuSLL=0._dp \n"]; 
WriteString[file,"TSOlluuSRR=0._dp \n"]; 
WriteString[file,"TSOlluuSRL=0._dp \n"]; 
WriteString[file,"TSOlluuSLR=0._dp \n"]; 
WriteString[file,"TSOlluuVRR=0._dp \n"]; 
WriteString[file,"TSOlluuVLL=0._dp \n"]; 
WriteString[file,"TSOlluuVRL=0._dp \n"]; 
WriteString[file,"TSOlluuVLR=0._dp \n"]; 
WriteString[file,"TSOlluuTLL=0._dp \n"]; 
WriteString[file,"TSOlluuTLR=0._dp \n"]; 
WriteString[file,"TSOlluuTRL=0._dp \n"]; 
WriteString[file,"TSOlluuTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeS2L2u,treeScalar, {}, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeS2L2u \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeS2L2u][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
Return[]; (* not necessary *) ,
S, (* Scalar penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TSOlluuSLL=TSOlluuSLL+ coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLL= & "<> StringReplace["coup1L coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLL,coup1L*coup2L*IMP2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRR=TSOlluuSRR+ coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRR= & "<> StringReplace["coup1R coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRR,coup1R*coup2R*IMP2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRL=TSOlluuSRL+ coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRL= & "<> StringReplace["coup1R coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRL,coup1R*coup2L*IMP2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSLR=TSOlluuSLR+ coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLR= & "<> StringReplace["coup1L coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLR,coup1L*coup2R*IMP2} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRR=TSOlluuVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLL=TSOlluuVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRL=TSOlluuVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLR=TSOlluuVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLL=TSOlluuTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLR=TSOlluuTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRL=TSOlluuTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRR=TSOlluuTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRR,0} " ];
,
  2, 
	 	 WriteStringFLB[file,"  TSOlluuSLL=TSOlluuSLL+ -0.5*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLL= & "<> StringReplace["-(coup1L coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLL,-(coup1L*coup2L*IMP2)/2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRR=TSOlluuSRR+ -0.5*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRR= & "<> StringReplace["-(coup1R coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRR,-(coup1R*coup2R*IMP2)/2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRL=TSOlluuSRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRL,0}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSLR=TSOlluuSLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRR=TSOlluuVRR+ 0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRR= & "<> StringReplace["(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRR,(coup1R*coup2L*IMP2)/2} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLL=TSOlluuVLL+ 0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLL= & "<> StringReplace["(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLL,(coup1L*coup2R*IMP2)/2} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRL=TSOlluuVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLR=TSOlluuVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLL=TSOlluuTLL+ -0.125*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLL= & "<> StringReplace["-(coup1L coup2L IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLL,-(coup1L*coup2L*IMP2)/8} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLR=TSOlluuTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRL=TSOlluuTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRR=TSOlluuTRR+ -0.125*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRR= & "<> StringReplace["-(coup1R coup2R IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRR,-(coup1R*coup2R*IMP2)/8} " ];
,
  3, 
	 	 WriteStringFLB[file,"  TSOlluuSLL=TSOlluuSLL+ -0.5*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLL= & "<> StringReplace["-(coup1L coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLL,-(coup1L*coup2L*IMP2)/2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRR=TSOlluuSRR+ -0.5*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRR= & "<> StringReplace["-(coup1R coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRR,-(coup1R*coup2R*IMP2)/2}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSRL=TSOlluuSRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSRL,0}, " ];
	 	 WriteStringFLB[file,"  TSOlluuSLR=TSOlluuSLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuSLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuSLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRR=TSOlluuVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLL=TSOlluuVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuVRL=TSOlluuVRL+ -0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVRL= & "<> StringReplace["-(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVRL,-(coup1R*coup2L*IMP2)/2} " ];
	 	 WriteStringFLB[file,"  TSOlluuVLR=TSOlluuVLR+ -0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuVLR= & "<> StringReplace["-(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuVLR,-(coup1L*coup2R*IMP2)/2} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLL=TSOlluuTLL+ 0.125*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLL= & "<> StringReplace["(coup1L coup2L IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLL,(coup1L*coup2L*IMP2)/8} " ];
	 	 WriteStringFLB[file,"  TSOlluuTLR=TSOlluuTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTLR,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRL=TSOlluuTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRL,0} " ];
	 	 WriteStringFLB[file,"  TSOlluuTRR=TSOlluuTRR+ 0.125*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSOlluuTRR= & "<> StringReplace["(coup1R coup2R IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TSOlluuTRR,(coup1R*coup2R*IMP2)/8} " ];
];]; 
]; 


