(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 15:56 on 16.12.2015 *) 
 
 
PrintDebug["   ... ",TreeV4Lcross]; 
NamesParticles =  {ChargedLepton, bar[ChargedLepton], ChargedLepton, bar[ChargedLepton]}; 
 NamesOperators =  {TVO4lSLLcross, TVO4lSRRcross, TVO4lSRLcross, TVO4lSLRcross, TVO4lVRRcross, TVO4lVLLcross, TVO4lVRLcross, TVO4lVLRcross, TVO4lTLLcross, TVO4lTLRcross, TVO4lTRLcross, TVO4lTRRcross}; 
 NeglectInsertionOrderTree[TreeV4Lcross] =  {}; 
NeglectCrossedDiagrams[TreeV4Lcross] = False; 
NameProcess = TreeV4Lcross; 
 
Generate[TreeV4Lcross][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {ChargedLepton, bar[ChargedLepton], ChargedLepton, bar[ChargedLepton]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[ChargedLepton,bar[ChargedLepton],ChargedLepton,bar[ChargedLepton],TreeV4Lcross,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeV4Lcross][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeV4Lcross] = masses 
]; 

WriteCodeObservablePreSARAH[TreeV4Lcross][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeV4Lcross] = masses; 
NeededCouplingsAllSaved[TreeV4Lcross] = couplings; 
NeededCombinations[TreeV4Lcross] = {{3, 1, 2, 2}, {3, 2, 1, 1}, {3, 2, 1, 2}, {3, 1, 2, 1}}; 
PrintDebug["     writing SPheno code for ",TreeV4Lcross]; 
MakeSubroutineTitle["CalculateTreeV4Lcross",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TVO4lSLLcross", "TVO4lSRRcross", "TVO4lSRLcross", "TVO4lSLRcross", "TVO4lVRRcross", "TVO4lVLLcross", "TVO4lVRLcross", "TVO4lVLRcross", "TVO4lTLLcross", "TVO4lTLRcross", "TVO4lTRLcross", "TVO4lTRRcross"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeV4Lcross \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 15:56 on 16.12.2015 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TVO4lSLLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lSRRcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lSRLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lSLRcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lVRRcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lVLLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lVRLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lVLRcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lTLLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lTLRcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lTRLcross \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TVO4lTRRcross \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeV4Lcross' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[ChargedLepton,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[ChargedLepton,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[ChargedLepton],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[ChargedLepton],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[ChargedLepton,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[ChargedLepton,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[ChargedLepton],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[ChargedLepton],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {ChargedLepton, bar[ChargedLepton], ChargedLepton, bar[ChargedLepton]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{ChargedLepton[{gt1}], bar[ChargedLepton][{gt2}], ChargedLepton[{gt3}], bar[ChargedLepton][{gt4}]}]<>"$} \n"];
WriteString[file,"TVO4lSLLcross=0._dp \n"]; 
WriteString[file,"TVO4lSRRcross=0._dp \n"]; 
WriteString[file,"TVO4lSRLcross=0._dp \n"]; 
WriteString[file,"TVO4lSLRcross=0._dp \n"]; 
WriteString[file,"TVO4lVRRcross=0._dp \n"]; 
WriteString[file,"TVO4lVLLcross=0._dp \n"]; 
WriteString[file,"TVO4lVRLcross=0._dp \n"]; 
WriteString[file,"TVO4lVLRcross=0._dp \n"]; 
WriteString[file,"TVO4lTLLcross=0._dp \n"]; 
WriteString[file,"TVO4lTLRcross=0._dp \n"]; 
WriteString[file,"TVO4lTRLcross=0._dp \n"]; 
WriteString[file,"TVO4lTRRcross=0._dp \n"]; 
WriteDiagramsObservable[TreeV4Lcross,{}, treeVector, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeV4Lcross \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeV4Lcross][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TVO4lSLLcross=TVO4lSLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLLcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRRcross=TVO4lSRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRRcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRLcross=TVO4lSRLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRLcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSLRcross=TVO4lSLRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lVRRcross=TVO4lVRRcross+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRRcross= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRRcross,-(coup1R*coup2R*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVLLcross=TVO4lVLLcross+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLLcross= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLLcross,-(coup1L*coup2L*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVRLcross=TVO4lVRLcross+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRLcross= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRLcross,-(coup1R*coup2L*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVLRcross=TVO4lVLRcross+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLRcross= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLRcross,-(coup1L*coup2R*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lTLLcross=TVO4lTLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTLRcross=TVO4lTLRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRLcross=TVO4lTRLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRRcross=TVO4lTRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRRcross,0} " ];
,
  2, 
	 	 WriteStringFLB[file,"  TVO4lSLLcross=TVO4lSLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLLcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRRcross=TVO4lSRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRRcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRLcross=TVO4lSRLcross+ -2.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRLcross= & "<> StringReplace["-2 coup1L coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRLcross,-2*coup1L*coup2L*IMP2}, " ];
	 	 WriteStringFLB[file,"  TVO4lSLRcross=TVO4lSLRcross+ -2.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLRcross= & "<> StringReplace["-2 coup1R coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLRcross,-2*coup1R*coup2R*IMP2} " ];
	 	 WriteStringFLB[file,"  TVO4lVRRcross=TVO4lVRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lVLLcross=TVO4lVLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lVRLcross=TVO4lVRLcross+ -1.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRLcross= & "<> StringReplace["-(coup1L coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRLcross,-(coup1L*coup2R*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVLRcross=TVO4lVLRcross+ -1.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLRcross= & "<> StringReplace["-(coup1R coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLRcross,-(coup1R*coup2L*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lTLLcross=TVO4lTLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTLRcross=TVO4lTLRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRLcross=TVO4lTRLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRRcross=TVO4lTRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRRcross,0} " ];
,
  3, 
	 	 WriteStringFLB[file,"  TVO4lSLLcross=TVO4lSLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLLcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRRcross=TVO4lSRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRRcross,0}, " ];
	 	 WriteStringFLB[file,"  TVO4lSRLcross=TVO4lSRLcross+ 2.*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSRLcross= & "<> StringReplace["2 coup1R coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSRLcross,2*coup1R*coup2L*IMP2}, " ];
	 	 WriteStringFLB[file,"  TVO4lSLRcross=TVO4lSLRcross+ 2.*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lSLRcross= & "<> StringReplace["2 coup1L coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lSLRcross,2*coup1L*coup2R*IMP2} " ];
	 	 WriteStringFLB[file,"  TVO4lVRRcross=TVO4lVRRcross+ -1.*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRRcross= & "<> StringReplace["-(coup1R coup2R IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRRcross,-(coup1R*coup2R*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVLLcross=TVO4lVLLcross+ -1.*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLLcross= & "<> StringReplace["-(coup1L coup2L IMP2)",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLLcross,-(coup1L*coup2L*IMP2)} " ];
	 	 WriteStringFLB[file,"  TVO4lVRLcross=TVO4lVRLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVRLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVRLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lVLRcross=TVO4lVLRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lVLRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lVLRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTLLcross=TVO4lTLLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTLRcross=TVO4lTLRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTLRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTLRcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRLcross=TVO4lTRLcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRLcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRLcross,0} " ];
	 	 WriteStringFLB[file,"  TVO4lTRRcross=TVO4lTRRcross+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TVO4lTRRcross= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteString[FKout,"  {TVO4lTRRcross,0} " ];
];,
S, (* Scalar penguins *) 
Return[]; (* not necessary *) ]; 
]; 


