(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 12:38 on 13.6.2016 *) 
 
 
PrintDebug["   ... ",Box2d2nu]; 
NamesParticles =  {DownQuark, bar[DownQuark], Neutrino, bar[Neutrino]}; 
 NamesOperators =  {BOddvvVRR, BOddvvVLL, BOddvvVRL, BOddvvVLR}; 
 NeglectInsertionOrderBox[Box2d2nu] = {}; 
NeglectCrossedDiagrams[Box2d2nu] = False; 
NameProcess = Box2d2nu; 
 
Generate[Box2d2nu][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {DownQuark, bar[DownQuark], Neutrino, bar[Neutrino]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[DownQuark,bar[DownQuark],Neutrino,bar[Neutrino],Box2d2nu,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[Box2d2nu][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[Box2d2nu] = masses 
]; 

WriteCodeObservablePreSARAH[Box2d2nu][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[Box2d2nu] = masses; 
NeededCouplingsAllSaved[Box2d2nu] = couplings; 
NeededCombinations[Box2d2nu] = {{2, 1, 1, 1}, {3, 1, 1, 1}, {3, 2, 1, 1}, {2, 1, 1, 2}, {3, 1, 1, 2}, {3, 2, 1, 2}, {2, 1, 1, 3}, {3, 1, 1, 3}, {3, 2, 1, 3}, {2, 1, 2, 1}, {3, 1, 2, 1}, {3, 2, 2, 1}, {2, 1, 2, 2}, {3, 1, 2, 2}, {3, 2, 2, 2}, {2, 1, 2, 3}, {3, 1, 2, 3}, {3, 2, 2, 3}, {2, 1, 3, 1}, {3, 1, 3, 1}, {3, 2, 3, 1}, {2, 1, 3, 2}, {3, 1, 3, 2}, {3, 2, 3, 2}, {2, 1, 3, 3}, {3, 1, 3, 3}, {3, 2, 3, 3}}; 
PrintDebug["     writing SPheno code for ",Box2d2nu]; 
MakeSubroutineTitle["CalculateBox2d2nu",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"BOddvvVRR", "BOddvvVLL", "BOddvvVRL", "BOddvvVLR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process Box2d2nu \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 12:38 on 13.6.2016 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: BOddvvVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOddvvVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOddvvVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: BOddvvVLR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateBox2d2nu' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[DownQuark,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[DownQuark,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[DownQuark],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[DownQuark],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[Neutrino,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[Neutrino,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[Neutrino],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[Neutrino],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {DownQuark, bar[DownQuark], Neutrino, bar[Neutrino]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{DownQuark[{gt1}], bar[DownQuark][{gt2}], Neutrino[{gt3}], bar[Neutrino][{gt4}]}]<>"$} \n"];
WriteString[file,"BOddvvVRR=0._dp \n"]; 
WriteString[file,"BOddvvVLL=0._dp \n"]; 
WriteString[file,"BOddvvVRL=0._dp \n"]; 
WriteString[file,"BOddvvVLR=0._dp \n"]; 
WriteDiagramsObservable[Box2d2nu,{}, {}, {}, {}, {}, {}, box, file];
WriteString[file,"BOddvvVRR=oo16pi2*BOddvvVRR \n"]; 
WriteString[file,"BOddvvVLL=oo16pi2*BOddvvVLL \n"]; 
WriteString[file,"BOddvvVRL=oo16pi2*BOddvvVRL \n"]; 
WriteString[file,"BOddvvVLR=oo16pi2*BOddvvVLR \n"]; 
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateBox2d2nu \n\n"]; 
]; 
AddBoxResultPreSARAH[Box2d2nu][top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given box diagram *) 
 
Switch[top, (* check in which order the external legs are glued to the box *) 
1, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4L*dd00[mF12, mF22, mS22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4R*dd00[mF12, mF22, mS22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2L*coup3L*coup4R*dd00[mF12, mF22, mS22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2R*coup3R*coup4L*dd00[mF12, mF22, mS22, mS12]} " ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-0.5*chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-(coup1R*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mS12, mS22])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-0.5*chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-(coup1L*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mS12, mS22])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2L*coup3L*coup4R*dd00[mF12, mF22, mS12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2R*coup3R*coup4L*dd00[mF12, mF22, mS12, mS22]} " ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2R*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2L*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]} " ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2L*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2R*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]} " ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+2.*chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["2 chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,2*coup1R*coup2L*coup3R*coup4R*dd00[mF12, mF22, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+2.*chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["2 chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,2*coup1L*coup2R*coup3L*coup4L*dd00[mF12, mF22, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mS12, mV22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mS12, mV22])} " ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+2.*chargefactor*coup1R*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["2 chargefactor coup1R coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,2*coup1R*coup2R*coup3R*coup4L*dd00[mF12, mF22, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+2.*chargefactor*coup1L*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["2 chargefactor coup1L coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,2*coup1L*coup2L*coup3L*coup4R*dd00[mF12, mF22, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4R I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mV12, mS22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4L I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mV12, mS22])} " ];
,
	FVVF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,16*coup1R*coup2R*coup3R*coup4R*dd00[mF12, mF22, mV22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,16*coup1L*coup2L*coup3L*coup4L*dd00[mF12, mF22, mV22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,4*coup1R*coup2R*coup3L*coup4L*dd00[mF12, mF22, mV22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,4*coup1L*coup2L*coup3R*coup4R*dd00[mF12, mF22, mV22, mV12]} " ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-2*coup1R*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-2*coup1L*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,4*coup1R*coup2R*coup3L*coup4L*dd00[mF12, mF22, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,4*coup1L*coup2L*coup3R*coup4R*dd00[mF12, mF22, mV12, mV22]} " ];
];,
2, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-1.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-(coup1R*coup2L*coup3L*coup4R*dd00[mF12, mF22, mS22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-1.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-(coup1L*coup2R*coup3R*coup4L*dd00[mF12, mF22, mS22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2L*coup3R*coup4L*dd00[mF12, mF22, mS22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2R*coup3L*coup4R*dd00[mF12, mF22, mS22, mS12])} " ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-1.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-(coup1R*coup2L*coup3L*coup4R*dd00[mF22, mF12, mS12, mS22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-1.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-(coup1L*coup2R*coup3R*coup4L*dd00[mF22, mF12, mS12, mS22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+0.5*chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["(chargefactor coup1R coup2L coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,(coup1R*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF22, mF12, mS12, mS22])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+0.5*chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["(chargefactor coup1L coup2R coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,(coup1L*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF22, mF12, mS12, mS22])/2} " ];
,
	FSVF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2R*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2L*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]} " ];
,
	FVSF, 
	 	 WriteString[file,"  int1=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]} " ];
,
	SFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4R*MMD0[mF1, mF2, mF22, mF12, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4L*MMD0[mF1, mF2, mF22, mF12, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2L*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2L coup3L coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2L*coup3L*coup4L*(C0D0check[mF22, mF12, mV22, mS12] - 2*dd00[mF22, mF12, mS12, mV22]))}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2R*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2R coup3R coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2R*coup3R*coup4R*(C0D0check[mF22, mF12, mV22, mS12] - 2*dd00[mF22, mF12, mS12, mV22]))} " ];
,
	VFFS, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2R*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF22, mF12, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2L*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF22, mF12, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2R*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3R coup4L (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2R*coup3R*coup4L*(C0D0check[mF22, mF12, mS22, mV12] - 2*dd00[mF22, mF12, mV12, mS22]))}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2L*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3L coup4R (I_1 - 2 I_2))",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2L*coup3L*coup4R*(C0D0check[mF22, mF12, mS22, mV12] - 2*dd00[mF22, mF12, mV12, mS22]))} " ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-4*coup1R*coup2R*coup3R*coup4R*(C0D0check[mF22, mV22, mV12, mF12] - 3*dd00[mF12, mF22, mV22, mV12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-4*coup1L*coup2L*coup3L*coup4L*(C0D0check[mF22, mV22, mV12, mF12] - 3*dd00[mF12, mF22, mV22, mV12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-4.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-4*coup1R*coup2R*coup3L*coup4L*C0D0check[mF22, mV22, mV12, mF12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-4.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-4*coup1L*coup2L*coup3R*coup4R*C0D0check[mF22, mV22, mV12, mF12]} " ];
,
	VFFV, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mF12, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mF12, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-4.*chargefactor*coup1R*coup2R*coup3R*coup4R*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-4 chargefactor coup1R coup2R coup3R coup4R (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-4*coup1R*coup2R*coup3R*coup4R*(C0D0check[mF22, mF12, mV22, mV12] - 3*dd00[mF22, mF12, mV12, mV22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-4.*chargefactor*coup1L*coup2L*coup3L*coup4L*(int1 - 3.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-4 chargefactor coup1L coup2L coup3L coup4L (I_1 - 3 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-4*coup1L*coup2L*coup3L*coup4L*(C0D0check[mF22, mF12, mV22, mV12] - 3*dd00[mF22, mF12, mV12, mV22])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,2*coup1R*coup2R*coup3L*coup4L*MMD0[mF1, mF2, mF22, mF12, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,2*coup1L*coup2L*coup3R*coup4R*MMD0[mF1, mF2, mF22, mF12, mV12, mV22]} " ];
];,
3, 
   Switch[type, (* Check the generic type of the diagram *) 
	FSSF, 
	 	 WriteString[file,"  int1=D00check(mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mS22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-0.5*chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-(chargefactor coup1R coup2L coup3R coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-(coup1R*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mS12])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-0.5*chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-(chargefactor coup1L coup2R coup3L coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-(coup1L*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mS12])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-1.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-(chargefactor coup1R coup2R coup3L coup4L I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-(coup1R*coup2R*coup3L*coup4L*dd00[mF12, mF22, mS22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-1.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-(chargefactor coup1L coup2L coup3R coup4R I_1)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-(coup1L*coup2L*coup3R*coup4R*dd00[mF12, mF22, mS22, mS12])} " ];
,
	SFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4L*dd00[mF22, mF12, mS12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4R*dd00[mF22, mF12, mS12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+0.5*chargefactor*coup1R*coup2R*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["(chargefactor coup1R coup2R coup3L coup4L I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,(coup1R*coup2R*coup3L*coup4L*MMD0[mF1, mF2, mF22, mF12, mS12, mS22])/2}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+0.5*chargefactor*coup1L*coup2L*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["(chargefactor coup1L coup2L coup3R coup4R I_2)/2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,(coup1L*coup2L*coup3R*coup4R*MMD0[mF1, mF2, mF22, mF12, mS12, mS22])/2} " ];
,
	FSVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mS12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mS12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mV22, mS12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mS12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4R*(C0D0check[mF22, mV22, mS12, mF12] - 2*dd00[mF12, mF22, mV22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4L*(C0D0check[mF22, mV22, mS12, mF12] - 2*dd00[mF12, mF22, mV22, mS12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2R*coup3L*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2R coup3L coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2L*coup3R*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2L coup3R coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mS12]} " ];
,
	FVSF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mS22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mS22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=D00check(mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["D_{27}(mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int3=MMD0(mF1, mF2, mF12, mF22, mS22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_3 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mS22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2R*coup3R*coup4L*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4L (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2R*coup3R*coup4L*(C0D0check[mF22, mS22, mV12, mF12] - 2*dd00[mF12, mF22, mS22, mV12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2L*coup3L*coup4R*(int1 - 2.*int2)\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4R (I_1 - 2 I_2)",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2L*coup3L*coup4R*(C0D0check[mF22, mS22, mV12, mF12] - 2*dd00[mF12, mF22, mS22, mV12])}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+chargefactor*coup1R*coup2L*coup3L*coup4L*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["chargefactor coup1R coup2L coup3L coup4L I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,coup1R*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+chargefactor*coup1L*coup2R*coup3R*coup4R*int3\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["chargefactor coup1L coup2R coup3R coup4R I_3",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,coup1L*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mS22, mV12]} " ];
,
	SFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mS12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mS12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF22, mF12, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF22, mF12, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,2*coup1R*coup2L*coup3L*coup4R*dd00[mF22, mF12, mS12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,2*coup1L*coup2R*coup3R*coup4L*dd00[mF22, mF12, mS12, mV22]} " ];
,
	VFFS, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mS22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mS22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+chargefactor*coup1R*coup2L*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["chargefactor coup1R coup2L coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,coup1R*coup2L*coup3R*coup4L*MMD0[mF1, mF2, mF22, mF12, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+chargefactor*coup1L*coup2R*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["chargefactor coup1L coup2R coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,coup1L*coup2R*coup3L*coup4R*MMD0[mF1, mF2, mF22, mF12, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+2.*chargefactor*coup1R*coup2R*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["2 chargefactor coup1R coup2R coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,2*coup1R*coup2R*coup3L*coup4L*dd00[mF22, mF12, mV12, mS22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+2.*chargefactor*coup1L*coup2L*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["2 chargefactor coup1L coup2L coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,2*coup1L*coup2L*coup3R*coup4R*dd00[mF22, mF12, mV12, mS22]} " ];
,
	FVVF, 
	 	 WriteString[file,"  int1=C0D0check(mF22, mV22, mV12, mF12)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["C0D0check(mF22, mV22, mV12, mF12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF12, mF22, mV22, mV12)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF12, mF22, mV22, mV12)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+-2.*chargefactor*coup1R*coup2R*coup3R*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["-2 chargefactor coup1R coup2R coup3R coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,-2*coup1R*coup2R*coup3R*coup4R*MMD0[mF1, mF2, mF12, mF22, mV22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+-2.*chargefactor*coup1L*coup2L*coup3L*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["-2 chargefactor coup1L coup2L coup3L coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,-2*coup1L*coup2L*coup3L*coup4L*MMD0[mF1, mF2, mF12, mF22, mV22, mV12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+-4.*chargefactor*coup1R*coup2L*coup3L*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["-4 chargefactor coup1R coup2L coup3L coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,-4*coup1R*coup2L*coup3L*coup4R*C0D0check[mF22, mV22, mV12, mF12]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+-4.*chargefactor*coup1L*coup2R*coup3R*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["-4 chargefactor coup1L coup2R coup3R coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,-4*coup1L*coup2R*coup3R*coup4L*C0D0check[mF22, mV22, mV12, mF12]} " ];
,
	VFFV, 
	 	 WriteString[file,"  int1=D00check(mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_1 = & "<> StringReplace["D_{27}(mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteString[file,"  int2=MMD0(mF1, mF2, mF22, mF12, mV12, mV22)\n" ];
	 	 WriteString[sphenoTeX,"I_2 = & "<> StringReplace["MMD0(mF1, mF2, mF22, mF12, mV12, mV22)",SA`SPhenoTeXSub]<>" \\\\ \n"];
	 	 WriteStringFLB[file,"  BOddvvVRR=BOddvvVRR+16.*chargefactor*coup1R*coup2R*coup3R*coup4R*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRR= & "<> StringReplace["16 chargefactor coup1R coup2R coup3R coup4R I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRR,16*coup1R*coup2R*coup3R*coup4R*dd00[mF22, mF12, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLL=BOddvvVLL+16.*chargefactor*coup1L*coup2L*coup3L*coup4L*int1\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLL= & "<> StringReplace["16 chargefactor coup1L coup2L coup3L coup4L I_1",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLL,16*coup1L*coup2L*coup3L*coup4L*dd00[mF22, mF12, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVRL=BOddvvVRL+2.*chargefactor*coup1R*coup2L*coup3L*coup4R*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVRL= & "<> StringReplace["2 chargefactor coup1R coup2L coup3L coup4R I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVRL,2*coup1R*coup2L*coup3L*coup4R*MMD0[mF1, mF2, mF22, mF12, mV12, mV22]}, " ];
	 	 WriteStringFLB[file,"  BOddvvVLR=BOddvvVLR+2.*chargefactor*coup1L*coup2R*coup3R*coup4L*int2\n" ];
	 	 WriteString[sphenoTeX,"  BOddvvVLR= & "<> StringReplace["2 chargefactor coup1L coup2R coup3R coup4L I_2",SA`SPhenoTeXSub] <>" \\\\ \n" ];
	 	 WriteString[FKout,"  {BOddvvVLR,2*coup1L*coup2R*coup3R*coup4L*MMD0[mF1, mF2, mF22, mF12, mV12, mV22]} " ];
];]; 
]; 


