(* Code automatically generated by 'PreSARAH' *) 
(* Expressions for amplitudes are obtained by FeynArts/FormCalc *) 
(* This file is supposed to be loaded and used by SARAH *) 
(* Created at 11:24 on 15.12.2015 *) 
 
 
PrintDebug["   ... ",TreeS4d]; 
NamesParticles =  {DownQuark, bar[DownQuark], DownQuark, bar[DownQuark]}; 
 NamesOperators =  {TSO4dSLL, TSO4dSRR, TSO4dSRL, TSO4dSLR, TSO4dVRR, TSO4dVLL, TSO4dVRL, TSO4dVLR, TSO4dTLL, TSO4dTLR, TSO4dTRL, TSO4dTRR}; 
 NeglectInsertionOrderTree[TreeS4d] =  {}; 
NeglectCrossedDiagrams[TreeS4d] = False; 
NameProcess = TreeS4d; 
 
ColorFlow = ColorDelta[1, 2] ColorDelta[3, 4]; 
 
Generate[TreeS4d][file_]:=Block[{i,j,k}, 
 

 (* Creating all possible processes; extract information about involved masses/couplings *) 


(* ------------------------------- *)
(* {DownQuark, bar[DownQuark], DownQuark, bar[DownQuark]} *)
(* ------------------------------- *)
 
GetInformtion4FermionProcess[DownQuark,bar[DownQuark],DownQuark,bar[DownQuark],TreeS4d,file]; 
NeededMassesAll=Intersection[NeededMasses];
NeededCouplingsAll=Intersection[NeededCouplings];
WriteCodeObservablePreSARAH[TreeS4d][NeededMassesAll,NeededCouplingsAll,TreeContributionsScalar,TreeContributionsVector,WaveContributionsScalar,WaveContributionsVector,WaveContributionsPhoton,PenguinContributionsScalar,PenguinContributionsVector,PenguinContributionsPhoton,BoxContributions,file]; 
NeededMassAllSaved[TreeS4d] = masses 
]; 

WriteCodeObservablePreSARAH[TreeS4d][masses_,couplings_,treeScalar_,treeVector_,waveScalar_,waveVector_,wavePhoton_,penguinScalar_,penguinVector_,penguinPhoton_,box_,file_] :=Block[{i,j,k,fermions,scalars}, 
 
NeededMassesAllSaved[TreeS4d] = masses; 
NeededCouplingsAllSaved[TreeS4d] = couplings; 
NeededCombinations[TreeS4d] = {{3, 1, 3, 1}, {3, 2, 3, 2}, {2, 1, 2, 1}}; 
PrintDebug["     writing SPheno code for ",TreeS4d]; 
MakeSubroutineTitle["CalculateTreeS4d",Flatten[{masses,couplings}],{"gt1","gt2","gt3","gt4","OnlySM"}, 
{"TSO4dSLL", "TSO4dSRR", "TSO4dSRL", "TSO4dSLR", "TSO4dVRR", "TSO4dVLL", "TSO4dVRL", "TSO4dVLR", "TSO4dTLL", "TSO4dTLR", "TSO4dTRL", "TSO4dTRR"},file]; 
WriteString[file,"! ---------------------------------------------------------------- \n"]; 
WriteString[file,"! Code based on automatically generated SARAH extensions by 'PreSARAH' \n"]; 
WriteString[file,"! Expressions for amplitudes are obtained by FeynArts/FormCalc \n"]; 
WriteString[file,"! Based on user input for process TreeS4d \n"]; 
WriteString[file,"! 'PreSARAH' output has been generated  at 11:24 on 15.12.2015 \n"]; 
WriteString[file,"! ---------------------------------------------------------------- \n \n"]; 
 
 
WriteString[file,"Implicit None \n"]; 
MakeVariableList[Flatten[{couplings,masses}],",Intent(in)",file];
WriteString[file,"Integer,Intent(in) :: gt1, gt2,gt3,gt4 \n"];
WriteString[file,"Logical, Intent(in) :: OnlySM \n"];
WriteString[file,"Integer :: iprop, i1, i2, i3, i4 \n"];
WriteString[file,"Real(dp) :: MassEx1,MassEx2,MassEx3,MassEx4, MassEx12,MassEx22,MassEx32,MassEx42 \n"];
WriteString[file,"Complex(dp), Intent(out) :: TSO4dSLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dSRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dSRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dSLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dVRR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dVLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dVRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dVLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dTLL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dTLR \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dTRL \n"]; 
WriteString[file,"Complex(dp), Intent(out) :: TSO4dTRR \n"]; 
WriteString[file,"Complex(dp) :: vertex1L, vertex1R, vertex2L, vertex2R \n"];
WriteString[file,"Real(dp) ::  MP, MP2, IMP2, IMP, MFin, MFin2, IMFin, IMFin2, Finite  \n"];
WriteString[file,"Real(dp) ::  MS1, MS12, MS2, MS22, MF1, MF12, MF2, MF22, MV1, MV12, MV2, MV22  \n"];
WriteString[file,"Complex(dp) ::  chargefactor  \n"];
WriteString[file,"Complex(dp) ::  coup1L, coup1R, coup2L, coup2R, coup3L, coup3R, coup3, coup4L, coup4R \n\n"];

WriteString[file,"Complex(dp) ::  int1,int2,int3,int4,int5,int6,int7,int8 \n\n"];

WriteString[file,"Iname=Iname+1 \n"];
WriteString[file,"NameOfUnit(Iname)='CalculateTreeS4d' \n
"];
 
AddCalcSquaredMasses[masses,file]; 
(* Initaliziation *)
WriteString[file,"Finite=1._dp \n"];
WriteString[file,"MassEx1="<>SPhenoMass[DownQuark,gt1]<>"  \n"];
WriteString[file,"MassEx12="<>SPhenoMassSq[DownQuark,gt1]<>" \n"];
WriteString[file,"MassEx2="<>SPhenoMass[bar[DownQuark],gt2]<>"  \n"];
WriteString[file,"MassEx22="<>SPhenoMassSq[bar[DownQuark],gt2]<>" \n"];
WriteString[file,"MassEx3="<>SPhenoMass[DownQuark,gt3]<>"  \n"];
WriteString[file,"MassEx32="<>SPhenoMassSq[DownQuark,gt3]<>" \n"];
WriteString[file,"MassEx4="<>SPhenoMass[bar[DownQuark],gt4]<>"  \n"];
WriteString[file,"MassEx42="<>SPhenoMassSq[bar[DownQuark],gt4]<>" \n"];
WriteString[file,"! ------------------------------ \n "];
WriteString[file,"! Amplitudes for external states \n "];
WriteString[file,"! {DownQuark, bar[DownQuark], DownQuark, bar[DownQuark]} \n "];
WriteString[file,"! ------------------------------ \n \n"];
WriteString[sphenoTeX,"\\section{External states: $"<>TeXOutput[{DownQuark[{gt1}], bar[DownQuark][{gt2}], DownQuark[{gt3}], bar[DownQuark][{gt4}]}]<>"$} \n"];
WriteString[file,"TSO4dSLL=0._dp \n"]; 
WriteString[file,"TSO4dSRR=0._dp \n"]; 
WriteString[file,"TSO4dSRL=0._dp \n"]; 
WriteString[file,"TSO4dSLR=0._dp \n"]; 
WriteString[file,"TSO4dVRR=0._dp \n"]; 
WriteString[file,"TSO4dVLL=0._dp \n"]; 
WriteString[file,"TSO4dVRL=0._dp \n"]; 
WriteString[file,"TSO4dVLR=0._dp \n"]; 
WriteString[file,"TSO4dTLL=0._dp \n"]; 
WriteString[file,"TSO4dTLR=0._dp \n"]; 
WriteString[file,"TSO4dTRL=0._dp \n"]; 
WriteString[file,"TSO4dTRR=0._dp \n"]; 
WriteDiagramsObservable[TreeS4d,treeScalar, {}, {},  {}, {}, {}, {}, file];
WriteString[file,"Iname=Iname-1\n\n"]; 
WriteString[file,"End Subroutine CalculateTreeS4d \n\n"]; 
]; 
AddTreeResultPreSARAH[TreeS4d][prop_,top_,type_,file_]:=Block[{}, 

 (* This routine returns the generic expression for the amplitude of a given triangle diagram *) 
 
Switch[prop,
V, (* Vector penguins *) 
Return[]; (* not necessary *) ,
S, (* Scalar penguins *) 
 Switch[top,  (* Check topology *) 
  1, 
	 	 WriteStringFLB[file,"  TSO4dSLL=TSO4dSLL+ coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLL= & "<> StringReplace["coup1L coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRR=TSO4dSRR+ coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRR= & "<> StringReplace["coup1R coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRL=TSO4dSRL+ coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRL= & "<> StringReplace["coup1R coup2L IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSLR=TSO4dSLR+ coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLR= & "<> StringReplace["coup1L coup2R IMP2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRR=TSO4dVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLL=TSO4dVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRL=TSO4dVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLR=TSO4dVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLL=TSO4dTLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLR=TSO4dTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRL=TSO4dTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRR=TSO4dTRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  2, 
	 	 WriteStringFLB[file,"  TSO4dSLL=TSO4dSLL+ -0.5*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLL= & "<> StringReplace["-(coup1L coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRR=TSO4dSRR+ -0.5*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRR= & "<> StringReplace["-(coup1R coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRL=TSO4dSRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSLR=TSO4dSLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRR=TSO4dVRR+ 0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRR= & "<> StringReplace["(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLL=TSO4dVLL+ 0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLL= & "<> StringReplace["(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRL=TSO4dVRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLR=TSO4dVLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLL=TSO4dTLL+ -0.125*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLL= & "<> StringReplace["-(coup1L coup2L IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLR=TSO4dTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRL=TSO4dTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRR=TSO4dTRR+ -0.125*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRR= & "<> StringReplace["-(coup1R coup2R IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
,
  3, 
	 	 WriteStringFLB[file,"  TSO4dSLL=TSO4dSLL+ -0.5*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLL= & "<> StringReplace["-(coup1L coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRR=TSO4dSRR+ -0.5*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRR= & "<> StringReplace["-(coup1R coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSRL=TSO4dSRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dSLR=TSO4dSLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dSLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRR=TSO4dVRR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLL=TSO4dVLL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVRL=TSO4dVRL+ -0.5*coup1R*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVRL= & "<> StringReplace["-(coup1R coup2L IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dVLR=TSO4dVLR+ -0.5*coup1L*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dVLR= & "<> StringReplace["-(coup1L coup2R IMP2)/2",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLL=TSO4dTLL+ 0.125*coup1L*coup2L*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLL= & "<> StringReplace["(coup1L coup2L IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTLR=TSO4dTLR+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTLR= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRL=TSO4dTRL+ 0.\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRL= & "<> StringReplace["0",SA`SPhenoTeXSub]<>" \\\\ \n" ];
	 	 WriteStringFLB[file,"  TSO4dTRR=TSO4dTRR+ 0.125*coup1R*coup2R*IMP2\n" ];
	 	 WriteString[sphenoTeX,"  TSO4dTRR= & "<> StringReplace["(coup1R coup2R IMP2)/8",SA`SPhenoTeXSub]<>" \\\\ \n" ];
];]; 
]; 


